### ISSUE TITLE
Presentation

### ISSUE THREAD

**Issue by lioliosn** [auth-it-center/eurep-staff-pres#8]
@kkaraogl Κώστα σου στέλνω τα slides που έχω ήδη ετοιμάσει σχετικά με το EWP. Επομένως το γενικό intro δεν θα χρειαστεί από την πλευρά σας.
[Pages from STW_2019_Workshop 1.pdf](https://github.com/auth-it-center/eurep-staff-pres/files/3657569/Pages.from.STW_2019_Workshop.1.pdf)

**Comment by kkaraogl** [comment]
Ok Νίκο, thanks.

**Comment by lioliosn** [comment]
@kkaraogl @tsiakmaki παιδιά έχουμε κάτι έτοιμο? Επίσης χρειάζομαι ένα όνομα για την παρουσίαση (ποιος θα την κάνει) για να το βάλουμε στο τελικό πρόγραμμα που ετοιμάζουμε.

**Comment by kkaraogl** [comment]
Νίκο, εγώ θα την κάνω την παρουσίαση, οπότε my name. Θα βρω ένα τρόπο να μπορείς να την βλέπεις live και θα σου στείλω email.
